import type { Metadata } from "next";
import "./globals.css";
import { lexend } from "./font";
import { Navbar } from "@/components/my-ui/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.className} antialiased`}>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
